"""Defines constants shared by record types and record fields."""

RECORD_SIZE = 94

FILE_HEADER_RECORD_TYPE_CODE = 1
FILE_HEADER_PRIORITY_CODE = 1
FILE_HEADER_DEFAULT_FILE_ID_MODIFIER = 'A'
FILE_HEADER_BLOCKING_FACTOR = 10
FILE_HEADER_FORMAT_CODE = 1

BATCH_HEADER_RECORD_TYPE_CODE = 5
BATCH_HEADER_DEFAULT_SERVICE_CLASS_CODE = 200
BATCH_HEADER_DEFAULT_STANDARD_ENTRY_CLASS_CODE = 'PPD'
BATCH_HEADER_DEFAULT_ORIGINATOR_STATUS_CODE = 1
